### ISSUE TITLE
I ran the command to create the mailbox unrecognized

### ISSUE THREAD

**Issue by l617388617** [cloudsoft/winrm4j#121]
'enable-mailbox' is not recognized as an internal or external command,

I want to run a remote command to create a mailbox on exchange, but I can't. Thanks

**Comment by aledsage** [comment]
It sounds like you are looking for help with the commands to execute over winrm or in powershell. The focus of this tool, and thus the jira issues, is a java library giving the capability to execute commands over winrm.

Therefore closing this issue.
