### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by rahulcoode90** [cloudsoft/winrm4j#13]
Please update Readme.md file as after the changes to winrm4j there is no Session.class file and also please provide some examples

**Comment by neykov** [comment]
Thank you for the feedback. The readme is updated in https://github.com/cloudsoft/winrm4j/pull/9, to be merged soon.

**Comment by rahulcoode90** [comment]
Does this also support the domain authentication as while using pywinrm we can use kerberos authentication with that..if yes, how?

**Comment by neykov** [comment]
Yes, the project supports kerberos, but we haven't tested it yet so there are not examples and recommended setup.
For starters you can try including the [jCIFS](https://jcifs.samba.org/) library, and then configuring it as:
```
            Config.registerSmbURLHandler();
            Config.setProperty("jcifs.smb.client.domain", "DOMAIN");
            Config.setProperty("jcifs.smb.client.username", "Administrator");
            Config.setProperty("jcifs.smb.client.password", "PASSWORD");
```
Also configure kerberos as described in https://docs.oracle.com/javase/7/docs/technotes/guides/security/jgss/tutorials/KerberosReq.html.

We are working to support kerberos, NTLM and certificate auth out of the box currently.

**Comment by rahulcoode90** [comment]
Thanks for the info. I am looking forward for support of the kerberos, NTLM and certificate auth out of the box. Once done please update the readme file

**Comment by neykov** [comment]
#9 merged, README is updated to reflect current support.
