### ISSUE TITLE
Request timeout when executing long running commands

### ISSUE THREAD

**Issue by bostko** [cloudsoft/winrm4j#15]
After running a command which is executing longer than 10 minutes I get this exception:
```
javax.xml.ws.soap.SOAPFaultException: The WS-Management service cannot complete the operation within the time specified in OperationTimeout.  
```

**Comment by neykov** [comment]
You can change the default `operationTimeout` when creating the `WinRmTool`. The [default is 1 minute](https://github.com/cloudsoft/winrm4j/blob/master/client/src/main/java/io/cloudsoft/winrm4j/client/WinRmClient.java#L70)  (kept for compatibility with old version), but there could be a bug increasing it to 10 minutes.

**Comment by bostko** [comment]
@neykov I think this is different.
It is the same in pywinrm.

Check 
https://github.com/diyan/pywinrm/blob/master/winrm/transport.py#L56
https://github.com/diyan/pywinrm/blob/master/winrm/transport.py#L108

http://stackoverflow.com/questions/9536616/setting-socket-read-timeout-with-javax-xml-soap-soapconnection

**Comment by neykov** [comment]
@bostko `operationTimeout` is per-command timeout, send along with the command to the service. The WinRM service is responsible for applying it (ant returning the error you are seeing). 
The one you are referring to is a connection level timeout, similar to the changes in #14. It's applied by the client side.

**Comment by neykov** [comment]
fixed in https://github.com/cloudsoft/winrm4j/pull/14
