### ISSUE TITLE
Kerberos Auth + winrm4j

### ISSUE THREAD

**Issue by rahulcoode90** [cloudsoft/winrm4j#17]
I have used JAAS + kerberos auth for the domain authentication of the user but not able to use the cached ticket with winrm4j module as WinRmTool.connect() accepts three arguments.!! I am not able to use cached ticket with it.

**Comment by neykov** [comment]
@rahulcoode90 If you have already authenticated, then you can pass null values for username and password. Java will reach out to the OS to get the needed info.

**Comment by rahulcoode90** [comment]
We cannot pass null values for username and password as it will give an error because in WinRmClient.java file you have implemented a function which is checking that these values should not be null

**Comment by neykov** [comment]
@rahulcoode90 The check at https://github.com/cloudsoft/winrm4j/blob/master/winrm4j/src/main/java/io/cloudsoft/winrm4j/winrm/WinRmTool.java#L53 will prevent passing null values. But if it's still an issue you could try with empty string instead.

**Comment by rahulcoode90** [comment]
I tried with empty strings it is still generating the error.. My problem is that i have to authenticate the user in domain environment. I have used JAAS + kerberos to authenticate the user but winrm4j module is not able to use the cached ticket and use to login to that user and execute commands.

**Comment by rahulcoode90** [comment]
Hey i got it working.Thanks for your help

**Comment by neykov** [comment]
Great work @rahulcoode90, it's nice to hear this combination is also working.
Out of curiosity, did you have to use jCIFS, or the standard java functionality was enough to get it working?

**Comment by rahulcoode90** [comment]
standard java functionality was enough to get it working. I did not used jCIFS. I used kinit to login and cached the ticket and java will automatically use the cached ticket. You just have to take care of the cached ticket expiry date in your code.

**Comment by neykov** [comment]
That's very useful to know, thanks for reporting back.
