### ISSUE TITLE
TODOs regarding the build and other non critical comments

### ISSUE THREAD

**Issue by bostko** [cloudsoft/winrm4j#18]
`client/pom.xml` line 173
Would be nice to keep the META-INF/wsdl location as that's where the wsgen tool is looking at on the classpath.

`client/pom.xml`
Move cxf dependencies to the jax-ws-cxf profile.
Add a line note

`client/pom.xml` 
Should use the file which the maven-dependency-plugin plugin has extracted above. Don't rely on the service being there (will be fetched from a maven repo if missing).

**Comment by neykov** [comment]
Also supporting `https` with `BASIC` auth (which means using `HttpComponents` client for all cases).

**Comment by bostko** [comment]
These are all addressed in winrm 0.3.5 so closing the issue.
