### ISSUE TITLE
WinRM4j CliClient doesn't stop

### ISSUE THREAD

**Issue by bostko** [cloudsoft/winrm4j#21]
The current `CliClient` class which Svet had wrote doesn't shutdown, you have to press Ctrl+C to exit each time invoking the `Cli.main`.
There is some IO thread pool which is CXF is always keeping the cli client cannot stop.
I tested it and it is not a problem. I run more than 15 clients through Apache Brooklyn and the number of threads remained 8.
RAM usage increased with about 10% only which is normal.

I have to dig first how to shutdown properly the pool of Bus objects in CXF.

 I can either shutdown each Bus, when command is completed or better I want to find a hook so I can shutdown the pool of Bus objects at the end of the program.

**Comment by awdamle** [comment]
@bostko Is the above issue fixed? Any plan on which release will have the fix? Is there any workaround in the current (0.3.5) version to shutdown the thread so that the thread doesn't stay running in the background?

**Comment by bostko** [comment]
It is fixed for the general case
https://github.com/cloudsoft/winrm4j/blob/master/client/src/main/java/io/cloudsoft/winrm4j/client/CliClient.java#L39
However still have to manually stop the process when error happens while executing a command.

**Comment by neykov** [comment]
Fixed in https://github.com/cloudsoft/winrm4j/pull/43

**Comment by neykov** [comment]
Fix included in the just released winrm4j 5.0.0
