### ISSUE TITLE
Please update Readme

### ISSUE THREAD

**Issue by rahulcoode90** [cloudsoft/winrm4j#22]
Please update Readme file for 0.3.0 version. As i am trying to use new version but my code  is not working which i wrote using 0.2.0 version.(WinRmTool.connect() method deprecated)

**Comment by rahulcoode90** [comment]
Anyone of the contributors please rply

**Comment by neykov** [comment]
Updated at https://github.com/cloudsoft/winrm4j/pull/29

**Comment by neykov** [comment]
README is up to date for the new winrm4j 5.0.0 release.
