### ISSUE TITLE
Connection to custom endpoints

### ISSUE THREAD

**Issue by petrolnt** [cloudsoft/winrm4j#41]
Hi, thank you for this great library. I try use it in my project, and have one issue. In version WinRM 3.0 and in latest versions there are feature that creating custom configurations with restricted access to some comandlets and PowerShell modules. Please describe me how i can connect to custom endpoint using your library?

**Comment by neykov** [comment]
@petrolnt You can specify a custom endpoint in the builder as first argument:
```
WinRmTool.Builder.builder("https://host:5986/wsman", "Administrator", "pa55w0rd!");
```

**Comment by petrolnt** [comment]
Thanks for the answer, but I think I asked the question incorrectly. I created a custom configuration with a limited set of cmdlets via cmdlet Register-PSSessionConfiguration. The configuration is called CustomConfig. Using the URI https://myserver:5986/wsman/ i connect using default pssession configuration that called microsoft.powershell. There are some chances to using my not default configuration called CustomConfig via your library?
Thank you.

**Comment by neykov** [comment]
No this is not supported at present.
`winrm4j` is actually talking to the server using the winrs protocol (plain cmd environment). Powershell commands are executed by calling [`powershell -encodedcommand <base64'd command>`](https://github.com/cloudsoft/winrm4j/blob/master/winrm4j/src/main/java/io/cloudsoft/winrm4j/winrm/WinRmTool.java#L259).
If it's possible to apply the custom configuration you've created on the local session then it could work.

One workaround could be to take your powershell commands and wrap them in a `Invoke-Command` such as:
```
Invoke-Command -ComputerName localhost -ConfigurationName CustomConfig -ScriptBlock <commands to execute in the limited session>
```

**Comment by petrolnt** [comment]
Thanks for the answer, will test it later.
Thanks
