### ISSUE TITLE
Error message: No handlers could be found for logger "_socket"

### ISSUE THREAD

**Issue by aledsage** [cloudsoft/winrm4j#5]
As described at http://stackoverflow.com/questions/33516826/apache-brooklyn-0-8-0-incubation-no-handlers-could-be-found-for-logger-socket

One can hit the error message below:

    No handlers could be found for logger "_socket"

This error comes from jython: described at http://bugs.jython.org/issue2253, and a fix (within python code) at https://hg.python.org/jython/rev/e37122c32d8a.

We could presumably fix this by either including the python fix below (e.g. in `__init__.py`), or by upgrading to a newer version of jython:

    log = logging.getLogger("_socket")
    log.setLevel(level=logging.WARNING)

(There is a proposal to re-write winrm4j in pure Java, but that hasn't been done yet).

**Comment by neykov** [comment]
Fixed in https://github.com/cloudsoft/winrm4j/pull/8
