### ISSUE TITLE
Re-write winrm4j in pure Java

### ISSUE THREAD

**Issue by aledsage** [cloudsoft/winrm4j#6]
It would be good to re-write winrm4j in pure Java, so that it does not need to pull in jython.

This would massively reduce the size of the binary, make winrm4j more appealing to a wider audience, and would also help with OSGi problems for downstream projects (jython isn't packaged as OSGi bundles I believe).

**Comment by neykov** [comment]
Fixed in https://github.com/cloudsoft/winrm4j/pull/8
