### ISSUE TITLE
OperationTimeout for WinRmTool is not working

### ISSUE THREAD

**Issue by awdamle** [cloudsoft/winrm4j#67]
I have set the OperationTimeout on the WinRmTool object using its setOperationTimeout method and passing it a timeout value in milisecs. However, when I run a long running command on a remote Windows node, it is not timing out even after the timeout interval has lapsed. It appears as if that timeout value is simply ignored. Control returns back from the executeCommand method only after the entire command has completed execution. Can you please help?

**Comment by neykov** [comment]
Hi @awdamle. `OperationTimeout` has a different use. It specifies the poll period on the server - how long the server blocks before sending a response. It's main use is when long running connections fail (NAT timing out for example), to decrease the period for which a connection sits idle.

**Comment by awdamle** [comment]
@neykov Thanks for the clarification. I think I misunderstood the description for OperationTimeout which says "If operations cannot be completed in a specified time, the service returns a fault so that a client can comply with its obligations.". 
Anyway, once I execute a command on a remote Windows server using the executeCommand of WinRmTool, is there a way to terminate that command after a certain timeout interval has passed to handle the cases when the command gets stuck somewhere? Even if I implement a timeout mechanism in the client side code, I want to terminate/forcefully kill the command being executed on the remote server via winrm4j. Please advise.

**Comment by neykov** [comment]
Not with `WinRmTool` directly. It's meant as a very simple to use wrapper around `WinRmClient`. You could try switching to `WinRmClient` calls and call [`disconnect`](https://github.com/cloudsoft/winrm4j/blob/0.5.0/winrm4j/src/main/java/io/cloudsoft/winrm4j/winrm/WinRmTool.java#L248) when you need to end the session.

**Comment by awdamle** [comment]
@neykov Thanks for providing the alternative solution. When I call disconnect for the WinRmClient object, it is ending the session and aborting the command being run. However, I noticed that the active thread count in my application is increasing by 1 after every command execution even though I am using the latest version of winrm4j - 0.5.0. Any clues?

**Comment by awdamle** [comment]
@neykov The issue about the active thread count that I brought up in the earlier post was an internal issue in my application. I don't see any issue with winrm4j reserving any threads in v0.5.0. Thanks very much for your help!

**Comment by neykov** [comment]
:+1: thanks for the update @awdamle .
