### ISSUE TITLE
PS invocation of System.Diagnostics.Eventing.Reader methods

### ISSUE THREAD

**Issue by rmrmrmrm123** [cloudsoft/winrm4j#79]
Hi, I am new to GitHub, so please correct me if this is not the right place for such a post. I don't have an issue, but I have a question. I am planning to use winrm4j, to run PS commands on remote Windows hosts. The PS commands will be calling the .NET APIs in the System.Diagnostics.Eventing.Reader namespace, to collect Windows events. I would like to know, if anyone has ever tried it before? Or does anyone anticipate, any type of issues with this approach? Thanks in advance.

**Comment by aledsage** [comment]
@rmrmrmrm123 as long as you can write powershell to do this, then you should be able to call that through winrm and thus through winrm4j.

These docs contain some useful tips for executing winrm, and gotchas about exit codes and errors might not behave quite as you'd expect: https://docs.cloudsoft.io/blueprints/base-blueprints/winrm/index.html

I hope that answers your question - marking this issue as closed.
