### ISSUE TITLE
Can it support setSSLSocketFactory() when building WinRmTool?

### ISSUE THREAD

**Issue by zhizhu7** [cloudsoft/winrm4j#80]
It's supporting disableCertificateChecks which is handy when working in dev environment.
I am wondering whether it's possible to support setSSLSocketFactory() for by updating the methond "initializeClientAndService" in WinRmClient ?

Also, i tried to load a certificate into a KeyStore in run time inited a SSLContext with the KeyStore,  then set the DefaultSSLSocketFactory to the SSLContext before calling WinrmTool to execute a command over HTTPS.
It always throw a SSLHandShake error.

But if I import the certificate into "jre/lib/security/cacerts", the SSLHandShake error is gone, and HTTPS connection is working fine.

It's weird that it's behaving differently.
Thanks.

**Comment by aledsage** [comment]
This has been fixed in the 0.6.1 release - you can set `sslSocketFactory` on the builder (see https://github.com/cloudsoft/winrm4j/pull/93).
