### ISSUE TITLE
Method does not sets sslContext for TLSClientParameters

### ISSUE THREAD

**Issue by maujbs** [cloudsoft/winrm4j#85]
https://github.com/cloudsoft/winrm4j/blob/facb66ca29f44a17cc9d7c11a73c0abf6f52743f/client/src/main/java/io/cloudsoft/winrm4j/client/WinRmClient.java#L288-L290

I created a SSLContext and I expected that this will be set in TLSClientParameters, however the setSslContext method is never called by initializeClientAndService. Is there a way to set it?

This issue affects the application because it is not FIPS compliant!! Because it's using the default SSLContext instead of the one created by the app.

Thanks in advance

**Comment by aledsage** [comment]
This has been fixed in the 0.6.1 release - you can now pass the `SSLContext` into the builder (see https://github.com/cloudsoft/winrm4j/pull/92).
