### ISSUE TITLE
Leaking PIPEs in 0.6.0

### ISSUE THREAD

**Issue by nakomis** [cloudsoft/winrm4j#96]
After polling a windows server for some time, a downstream app starts failing with Too many open files errors. `lsof -p <PID> | wc -l` showed around 10000 open files

I  restarted the app, and `lsof` was stable at around 750. I then started polling the windows server using WinRM4j, `lsof` started to jump up by about 30 every 5 seconds (roughly the polling period the app was using). Once `lsof` hit around 2000, I stopped polling the server, with the app still running and `lsof` stabilised at around 2000

With the polling running, repeated runs of `jmap -histo <PID> | grep -i winrm` showed the number of `winrm` classes increasing over time. Again, after un-deploying the number stabilised at the 'high' figure

**Comment by aledsage** [comment]
This was fixed in 0.6.1. Closing issue.
